"""agregando columna tipo en la tala productos

Revision ID: 5647d4f0752c
Revises: 9c90db82c55b
Create Date: 2026-01-07 00:02:27.205482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5647d4f0752c'
down_revision = '9c90db82c55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
