"""agregando sistema de venta y detalle venta

Revision ID: 5adf68413a87
Revises: 5647d4f0752c
Create Date: 2026-01-07 00:10:47.154624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adf68413a87'
down_revision = '5647d4f0752c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('clientes_id', sa.Integer(), nullable=True),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.Column('empresas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientes_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresas_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('ventas_id', sa.Integer(), nullable=False),
    sa.Column('productos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productos_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['ventas_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_ventas')
    op.drop_table('ventas')
    # ### end Alembic commands ###
