"""Agregando clientes y mascotas

Revision ID: 8e5558c39d64
Revises: 54d813570559
Create Date: 2026-01-05 18:47:14.634332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5558c39d64'
down_revision = '54d813570559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('empresas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresas_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=30), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('clientes_id', sa.Integer(), nullable=False),
    sa.Column('empresas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientes_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresas_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
