"""Creando tabla historias clinicas

Revision ID: b14666deb3a9
Revises: e710c9f4be94
Create Date: 2026-01-06 12:28:57.181089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14666deb3a9'
down_revision = 'e710c9f4be94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=True),
    sa.Column('diagnostico', sa.String(length=250), nullable=True),
    sa.Column('tratamiento', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('mascotas_id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.Column('empresas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresas_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['mascotas_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historias')
    # ### end Alembic commands ###
