"""Agregando columna rol a usuarios

Revision ID: e710c9f4be94
Revises: 8e5558c39d64
Create Date: 2026-01-05 18:54:39.017983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e710c9f4be94'
down_revision = '8e5558c39d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
